# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: puppet_message/base.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class DingRequest(betterproto.Message):
    data: str = betterproto.string_field(1)


@dataclass
class DingResponse(betterproto.Message):
    pass
