# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: puppet_service.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
import grpclib


@dataclass
class DingRequest(betterproto.Message):
    data: str = betterproto.string_field(1)


@dataclass
class DingResponse(betterproto.Message):
    pass


class PuppetStub(betterproto.ServiceStub):
    async def ding(self, *, data: str = "") -> DingResponse:
        request = DingRequest()
        request.data = data

        return await self._unary_unary(
            "/puppet_grpc.Puppet/Ding", request, DingResponse,
        )
